# Generated by Django 4.1.2 on 2022-11-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_supplier_shopdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='shopdetail',
            new_name='shop_detail',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='supplier_address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplierName',
            new_name='supplier_name',
        ),
    ]
